### ISSUE TITLE
Tonal.Key in npm ?

### ISSUE THREAD

**Issue by Mdashdotdashn** [tonaljs/tonal#60]
Sorry for the possibly n00b question but after a `npm install tonal` I don't seem to be able to use the 'extensions'. I'm after Tonal.Key and Tonal.Detect...

Do I need to to anything special in order to use them ?
Thanks !

**Comment by Mdashdotdashn** [comment]
I found I needed to install tonal-key and tonal-detector. There's an error in the documentation though because it says to use `const Detect = require("tonal-detect")` while it is `const Detect = require("tonal-detector")`.

**Comment by nathanielkornet** [comment]
+1 on the docs being wrong. I was very confused about how to get the Detect functionality until i found this comment.

**Comment by glhrmv** [comment]
I don't know if things have changed since this issue was first posted, but `tonal-key` is included with `npm install tonal`. It isn't exported by `tonal`'s Tonal object though, so you'll still need to `require` or `import` `tonal-key`. I'm not exactly sure why `Key` is tagged as an extension, I think it should be included alongside `Scale` and the others, i.e., put it inside `packages/`. 
As for `Detect`, it seems the name was fixed so that the package on NPM **is** `tonal-detect`. This one is an extension so it (correctly) is not included with `npm install tonal`.

This is the most thorough JS library of this type I've found, but I'm not sure if it's still being developed. I would like to help filling out some more documentation examples but I'm unsure if my pull requests would even be seen.

**Comment by danigb** [comment]
Hi!

Yes, `Key` is now part of the distribution (in fact, my plan is to bundle all packages by default). The reason `tonal-detect` is not included (yet) is because it doesn't work for some edge cases and I didn't fix it.

> This is the most thorough JS library of this type I've found

Thanks! 👍 

> I'm not sure if it's still being developed...

Well, is not in active development, but I still maintain it. Any help, collaboration or PRs are more than welcome.

**Comment by danigb** [comment]
Just published
